@startuml
package "View" {
    [Tela de Cadastro de Aluno] --> [Controlador Aluno]
    [Tela de Login] --> [Controlador Autenticacao]
    [Tela de Consulta de Saldo] --> [Controlador Aluno]
    [Tela de Envio de Moedas] --> [Controlador Professor]
    [Tela de Troca de Moedas] --> [Controlador Aluno]
    [Tela de Cadastro de Empresa] --> [Controlador Empresa]
}

package "Controller" {
    [Controlador Aluno] --> [Servico Aluno]
    [Controlador Professor] --> [Servico Professor]
    [Controlador Empresa] --> [Servico Empresa]
    [Controlador Autenticacao] --> [Servico Autenticacao]
}

package "Model" {
    [Servico Aluno] --> [Repositorio Aluno]
    [Servico Professor] --> [Repositorio Professor]
    [Servico Empresa] --> [Repositorio Empresa]
    [Servico Autenticacao] --> [Repositorio Autenticacao]
}

[View] --> [Controller] : Interação do Usuário
[Controller] --> [Model] : Processamento e Atualização
[Model] --> [Database] : Persistência dos Dados
@enduml
