@startuml
left to right direction
actor "Aluno" as aluno
actor "Professor" as professor
actor "Empresa Parceira" as empresa
actor "Usuario" as usuario
actor "Relogio" as relogio

rectangle  sistema {
    usecase "Cadastrar no Sistema" as Cadastrar
    usecase "Login no Sistema" as Login
    usecase "Consultar Saldo e Histórico" as Saldo
    usecase "Trocar Moedas por Vantagem" as Resgate
    usecase "Enviar Moedas aos Alunos" as Enviar
    usecase "Cadastrar Vantagens" as Vantagem
    usecase "Notificar por email" as Notificacao
    usecase "Mandar Moedas Semestrais" as Receber

usuario <|-- aluno
usuario <|-- professor
usuario <|-- empresa

    aluno --> Cadastrar 
    usuario --> Login 
    aluno --> Saldo 
    aluno --> Resgate 
    professor --> Saldo 
    professor --> Enviar 
    relogio --> Receber 
    empresa --> Cadastrar 
    empresa --> Vantagem 
    
    


    Resgate --> Notificacao : <<include>>
    Enviar --> Notificacao : <<include>>
}
@enduml
